sudo: required
services: 
  - docker
before_install:
  - docker build -t dh008/chatbook -f Dockerfile.dev .
script:
  - docker run dh008/chatbook npm run test

deploy:
  - provider: elasticbeanstalk
  - region: sa-east-1
  - app: "docker-chatbook-env"
  - env: "DockerChatbook-env "
  - bucket_name: "elasticbeanstalk-sa-east-1-417139012467"
  - bucket_path: "docker-chatbook-env"
 
    on: 
      branch: master
    access_key_id: "AWS_ACCESS_KEY"
    secret_access_key: "$AWS_SECRET_KEY"
      secure: "$AWS_SECRET_KEY"
